name: Build
on:
  pull_request:
  push:
    branches:
      - trunk
jobs:
  build:
    uses: haokeyingxiao/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: HkagPlatformDemoData
